zapellass123/OpenEmailGenerator

- Pyramid_pattern.cpp
Added C++ code to print pyramid pattern.
> C++ Code to print pyramid pattern

- next greatest  element 1.cpp
> important question used multiple times in b/w code.

- D_Corrupted_Array.cpp
This is solution to a D problem of codeforces named corrupted array. I broke the problem into subproblems. this is an accepted solution.
> cf D problem

- Sudoku-Solver.cpp
Beginner level approach to sudoku
> Sudoku-Solver

- CircularLinkedList.cpp
Implemented Circular Linked List
> Implemented Circular Linked List

- DoublyLinkedList.cpp
Implemented Doubly Linked List
> Implemented Doubly Linked List

- QueueImplementation.cpp
> Implemented Queue using Array

- PhotoGallary.html
@zapellass123 please have a look
> Added Photo Gallery

- Reverse a doubly linked list.java
please consider my pull request
> Reverse a doubly linked list.java

- Digital Clock/Digital Clock.html
- Digital Clock/style.css
Hey ! I added a digital clock using Html, CSS, and JavaScript.
> Digital Clock Added

- Cyclic_sort.java
Added a java code for cyclic sort
> Java code for cyclic sort

- myFibonacciSearch.cpp
I have added fibonacci Search Program .Please merge it.
> fibonacci Search

- StartingPointOfLoopInLL.cpp
I have added starting point of a loop in linked list in C++ language.
> Added Starting Point Of A Loop In Linked List

- SegmentTree.cpp
> Added Segment Tree using cpp

- 2D Array's (WAVE Print).cpp
here below i have given some samples of input to check the quality of code
> Create 2D Array's (WAVE Print).cpp

- contains Duplicate II.cpp
Adding a leetcode solution of Contains Duplicate II problem on [leetcode](https://leetcode.com/problems/contains-duplicate-ii/)
> Create contains Duplicate II.cpp

- shellSort.cpp
C++ program to implement shell sort algorithm.
> ShellSort.cpp

- Strand_Sort.cpp
CPP program to implement Strand Sort
> StrandSort.cpp

- Stooge_Sort.cpp
C++ code to implement stooge sort
> Stooge sort

- Kth_Smallest_Number.c
C program to find K'th smallest element
> Kth_Smallest_Number.c

- library management system.py
hi please merge this pr in your repo under hactoberfest 2022
> library management system python

- StairCaseProblem.java
Added code for staircase problem in java
> Staircase Problem

- Bubble sort.go
- Merge sort in golang.go
sorting is need if you want to rearrange large data.
So i added some algo for Golang version.
> Merge sort and Bubble sort added in golang

- BFSGraph.cpp
implementation of BFS (Breadth First Search) of a graph in C++
> added BFSGraph.cpp

- LongestCommonSubsequence.java
Added code to find length of longest common subsequence in java
> Longest Common Subsequence

- cycle_Linked_List.cpp
> Created Cycles with Linked List

- merge2SortedLinkedLists.cpp
important program in linked lists
> merging two sorted linked lists

- Catalan_Number.cpp
A recursive function to find nth Catalan number
> Catalan_Number.cpp

- Super_Prime_Number.cpp
C++ program to print super primes less than or equal to n.
> Super_Prime_Number.cpp

- Trinomial_Triangle.cpp
CPP Program to print trinomial triangle.
> Trinomial_Triangle.cpp

- Juggler_Sequence.cpp
C++ implementation of Juggler Sequence
> Juggler_Sequence.cpp

- Rotate_a_linked_list.cpp
// C++ program to rotate a linked list counter clock wise
> Rotate_a_linked_list.cpp

- Tower_Of_Hanoi.php
function to solve tower of hanoi puzzle
> Tower_Of_Hanoi.php

- Queue_Reversal.cpp
CPP program to reverse a Queue
> CPP program to reverse a Queue

- Reverse First_K_elements_of_Queue.cpp
C++ program to reverse first k elements of a queue.
> Reversal of K element in queue

- The_Celebrity_Problem.cpp
> The_Celebrity_Problem.cpp
